spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillhunter
    username: skillhunter
    password: skillhunter
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
