spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillhunter
    username: skillhunter
    password: skillhunter
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:8081/realms/skill-hunter
